/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.monterroso.pract1.analizador.frontend;

import com.monterroso.pract1.analizador.backend.archivos.GeneradorReportes;
import com.monterroso.pract1.analizador.backend.modelos.ErrorLexico;
import com.monterroso.pract1.analizador.backend.modelos.Token;
import com.monterroso.pract1.analizador.backend.motor.AnalizadorLexico;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author seo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    private DefaultTableModel modeloTokens;
    private DefaultTableModel modeloErrores;
    private List<Token> ultimosTokens;
    private List<ErrorLexico> ultimosErrores;
    private int ultimoTotalLineas;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        modeloTokens = new javax.swing.table.DefaultTableModel(new Object[]{"#", "Lexema", "Tipo", "Fila", "Columna"}, 0); tablaTokens.setModel(modeloTokens);        
        modeloErrores = new javax.swing.table.DefaultTableModel( new Object[]{"Lexema", "Descripción", "Fila", "Columna"}, 0); tablaErrores.setModel(modeloErrores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraEstado = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonAbrir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonAnalizar = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        btnVerAFD = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        scrollEditor = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        separador = new javax.swing.JTabbedPane();
        scrollTokens = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        scrollErrores = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Lexico Promptzal");
        setBackground(new java.awt.Color(0, 0, 51));
        setUndecorated(false);

        barraEstado.setText("Listo");
        barraEstado.setBorder(BorderFactory.createEmptyBorder(4, 8, 4, 8));

        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);

        botonAbrir.setBackground(new java.awt.Color(153, 153, 153));
        botonAbrir.setForeground(new java.awt.Color(51, 51, 51));
        botonAbrir.setText("Abrir");
        botonAbrir.setMargin(new java.awt.Insets(5, 14, 2, 14));
        botonAbrir.addActionListener(this::botonAbrirActionPerformed);
        jToolBar1.add(botonAbrir);

        botonGuardar.setBackground(new java.awt.Color(153, 153, 153));
        botonGuardar.setForeground(new java.awt.Color(51, 51, 51));
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(this::botonGuardarActionPerformed);
        jToolBar1.add(botonGuardar);

        botonAnalizar.setBackground(new java.awt.Color(153, 153, 153));
        botonAnalizar.setForeground(new java.awt.Color(51, 51, 51));
        botonAnalizar.setText("Analizar");
        botonAnalizar.addActionListener(this::botonAnalizarActionPerformed);
        jToolBar1.add(botonAnalizar);

        botonReportes.setBackground(new java.awt.Color(153, 153, 153));
        botonReportes.setForeground(new java.awt.Color(51, 51, 51));
        botonReportes.setText("Generar Reportes");
        botonReportes.addActionListener(this::botonReportesActionPerformed);
        jToolBar1.add(botonReportes);

        btnVerAFD.setBackground(new java.awt.Color(153, 153, 153));
        btnVerAFD.setForeground(new java.awt.Color(51, 51, 51));
        btnVerAFD.setText("Ver AFD");
        btnVerAFD.setFocusable(false);
        btnVerAFD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerAFD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerAFD.addActionListener(this::btnVerAFDActionPerformed);
        jToolBar1.add(btnVerAFD);

        btnEstadisticas.setBackground(new java.awt.Color(153, 153, 153));
        btnEstadisticas.setForeground(new java.awt.Color(51, 51, 51));
        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.setFocusable(false);
        btnEstadisticas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstadisticas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstadisticas.addActionListener(this::btnEstadisticasActionPerformed);
        jToolBar1.add(btnEstadisticas);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        scrollEditor.setBorder(BorderFactory.createTitledBorder("Editor .pz"));

        editor.setColumns(20);
        editor.setRows(5);
        editor.setName(""); // NOI18N
        scrollEditor.setViewportView(editor);

        jSplitPane1.setTopComponent(scrollEditor);

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTokens.setViewportView(tablaTokens);

        separador.addTab("Tokens", scrollTokens);

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollErrores.setViewportView(tablaErrores);

        separador.addTab("Errores", scrollErrores);

        jSplitPane1.setRightComponent(separador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(barraEstado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraEstado))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        
        JFileChooser selector = new JFileChooser();
        
        selector.setFileFilter(new FileNameExtensionFilter("Archivos PromptZal (*.pz)", "pz"));
        
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                String contenido = Files.readString(selector.getSelectedFile().toPath());
                editor.setText(contenido);
                barraEstado.setText("Archivo abierto: " + selector.getSelectedFile().getName());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo abrir el archivo: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

        JFileChooser selector = new JFileChooser();
      
        selector.setFileFilter(new FileNameExtensionFilter("Archivos PromptZal (*.pz)", "pz"));
      
        if (selector.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            Path ruta = selector.getSelectedFile().toPath();
            if (!ruta.toString().endsWith(".pz")) {
                ruta = Path.of(ruta.toString() + ".pz");
            }
            try {
                Files.writeString(ruta, editor.getText());
                barraEstado.setText("Guardado en: " + ruta.getFileName());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo guardar el archivo: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed
       
        AnalizadorLexico analizador = new AnalizadorLexico(editor.getText());
      
        analizador.analizar();
    
        ultimosTokens = analizador.getTokens();
        ultimosErrores = analizador.getErrores();
        
        ultimoTotalLineas = analizador.getTotalLineas();
        
        modeloTokens.setRowCount(0);
  
        for (Token t : ultimosTokens) {
            modeloTokens.addRow(new Object[]{t.getNumero(), t.getLexema(), t.getTipo(), t.getFila(), t.getColumna()});
        }

        modeloErrores.setRowCount(0);
        for (ErrorLexico err : ultimosErrores) {
            modeloErrores.addRow(new Object[]{err.getLexema(), err.getDescripcion(), err.getFila(), err.getColumna()});
        }

        barraEstado.setText(ultimosTokens.size() + " tokens, " + ultimosErrores.size() + " errores.");
        
    }//GEN-LAST:event_botonAnalizarActionPerformed

    private void btnVerAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAFDActionPerformed
        VentanaAFD dialogo = new VentanaAFD(this, true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_btnVerAFDActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        
        if (ultimosTokens == null) {
            JOptionPane.showMessageDialog(this, "Primero presiona \"Analizar\".",
                    "Nada que mostrar", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VentanaEstadisticas dialogo = new VentanaEstadisticas(this, true, ultimosTokens, ultimosErrores, ultimoTotalLineas);
        dialogo.setVisible(true);
        
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
       
        if (ultimosTokens == null) {
            JOptionPane.showMessageDialog(this, "Primero presiona \"Analizar\".",
                    "Nada que reportar", JOptionPane.WARNING_MESSAGE);
            return;
        }
     
        GeneradorReportes reportes = new GeneradorReportes();
        
        reportes.generarReporteTokens(ultimosTokens, "reporte_tokens.html");
        reportes.generarReporteErrores(ultimosErrores, "reporte_errores.html");
        reportes.generarReporteEstadisticas(ultimosTokens, ultimosErrores, ultimoTotalLineas, "reporte_estadisticas.html"); 
        
        barraEstado.setText("Reportes generados en la carpeta del proyecto.");

    }//GEN-LAST:event_botonReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraEstado;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonAnalizar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnVerAFD;
    private javax.swing.JTextArea editor;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scrollEditor;
    private javax.swing.JScrollPane scrollErrores;
    private javax.swing.JScrollPane scrollTokens;
    private javax.swing.JTabbedPane separador;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaTokens;
    // End of variables declaration//GEN-END:variables
}
