/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.monterroso.pract1.analizador.frontend;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author seo
 */
public class VentanaAFD extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAFD.class.getName());

    /**
     * Creates new form VentanaAFD
     */
    public VentanaAFD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarImagen();

    }

    private static final String RUTA_IMAGEN = "afd_promptzal.png";

    private void cargarImagen(){
            
        File archivo = new File(RUTA_IMAGEN);
        if (archivo.exists()) {
            javax.swing.ImageIcon icono = new javax.swing.ImageIcon(archivo.getAbsolutePath());
            lblImagenAFD.setIcon(icono);
            lblImagenAFD.setText(null);
        } else {
            lblImagenAFD.setIcon(null);
            lblImagenAFD.setText("No se encontró " + RUTA_IMAGEN + ". Genera el AFD primero.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollImagenAFD = new javax.swing.JScrollPane();
        lblImagenAFD = new javax.swing.JLabel();
        btnRegenerar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnGuardarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblImagenAFD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scrollImagenAFD.setViewportView(lblImagenAFD);

        btnRegenerar.setText("Regenerar");
        btnRegenerar.addActionListener(this::btnRegenerarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnGuardarImagen.setText("Guardar Imagen");
        btnGuardarImagen.addActionListener(this::btnGuardarImagenActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollImagenAFD)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addComponent(btnGuardarImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollImagenAFD, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegenerar)
                    .addComponent(btnCerrar)
                    .addComponent(btnGuardarImagen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegenerarActionPerformed
       cargarImagen(); 
    }//GEN-LAST:event_btnRegenerarActionPerformed

    private void btnGuardarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarImagenActionPerformed
      
        java.io.File origen = new java.io.File(RUTA_IMAGEN);
       
        if (!origen.exists()) {
            JOptionPane.showMessageDialog(this, "No hay imagen generada todavía.",
                    "Nada que guardar", JOptionPane.WARNING_MESSAGE);
            return;
        }
        JFileChooser selector = new JFileChooser();
        
        selector.setSelectedFile(new File("afd_promptzal.png"));
        
        if (selector.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                java.nio.file.Files.copy(origen.toPath(), selector.getSelectedFile().toPath(),
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                JOptionPane.showMessageDialog(this, "Imagen guardada.");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo guardar: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarImagenActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaAFD dialog = new VentanaAFD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardarImagen;
    private javax.swing.JButton btnRegenerar;
    private javax.swing.JLabel lblImagenAFD;
    private javax.swing.JScrollPane scrollImagenAFD;
    // End of variables declaration//GEN-END:variables
}
