/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.monterroso.pract1.analizador.frontend;

import com.monterroso.pract1.analizador.backend.modelos.ErrorLexico;
import com.monterroso.pract1.analizador.backend.modelos.TipoToken;
import com.monterroso.pract1.analizador.backend.modelos.Token;
import java.awt.Color;

/**
 *
 * @author seo
 */
public class VentanaEstadisticas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName());

    /**
     * Creates new form VentanaEstadisticas
     */
    public VentanaEstadisticas(java.awt.Frame padre, boolean modal,
            java.util.List<Token> tokens,
            java.util.List<ErrorLexico> errores,
            int totalLineas) {
        super(padre, modal);
        initComponents();
        calcularYMostrar(tokens, errores, totalLineas);
    }

    private void calcularYMostrar(java.util.List<Token> tokens, java.util.List<ErrorLexico> errores, int totalLineas) {
        lblNumTokens.setText(String.valueOf(tokens.size()));
        lblNumLineas.setText(String.valueOf(totalLineas));
        lblNumErrores.setText(String.valueOf(errores.size()));

        javax.swing.table.DefaultTableModel modelo
                = new javax.swing.table.DefaultTableModel(new Object[]{"Tipo de token", "Cantidad"}, 0);

        for (TipoToken tipo : TipoToken.values()) {
            int contador = 0;
            for (Token t : tokens) {
                if (t.getTipo() == tipo) {
                    contador++;
                }
            }
            modelo.addRow(new Object[]{tipo, contador});
        }

        tablaFrecuencia.setModel(modelo);
        tablaFrecuencia.getColumnModel().getColumn(0).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable tabla, Object valor,
                    boolean seleccionado, boolean foco, int fila, int columna) {
                java.awt.Component celda = super.getTableCellRendererComponent(tabla, valor, seleccionado, foco, fila, columna);
                celda.setForeground(colorParaTipo((TipoToken) valor));
                return celda;
            }
        });
    }

    private Color colorParaTipo(TipoToken tipo) {
        switch (tipo) {
            case DIRECTIVA:
                return new java.awt.Color(77, 182, 172);
            case PALABRA_RESERVADA:
                return new java.awt.Color(100, 160, 220);
            case COMANDO_IA:
                return new java.awt.Color(199, 125, 187);
            case CONECTOR:
                return new java.awt.Color(224, 164, 88);
            case LITERAL_CADENA:
                return new java.awt.Color(224, 108, 117);
            case LITERAL_ENTERO:
            case LITERAL_DECIMAL:
                return new java.awt.Color(152, 195, 121);
            default:
                return java.awt.Color.LIGHT_GRAY;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTarjetaTokens = new javax.swing.JPanel();
        lblNumTokens = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelTarjetaLineas = new javax.swing.JPanel();
        lblNumLineas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelTarjetaErrores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNumErrores = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaFrecuencia = new javax.swing.JTable();
        btnCerrarEstadistica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadísticas del Análisis");

        panelTarjetaTokens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 5, true));
        panelTarjetaTokens.setPreferredSize(new java.awt.Dimension(250, 150));

        lblNumTokens.setFont(new java.awt.Font("Noto Sans", 0, 60)); // NOI18N
        lblNumTokens.setForeground(new java.awt.Color(0, 204, 255));
        lblNumTokens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumTokens.setText("4");

        jLabel2.setFont(new java.awt.Font("Noto Sans Black", 0, 13)); // NOI18N
        jLabel2.setText("Tokens");

        javax.swing.GroupLayout panelTarjetaTokensLayout = new javax.swing.GroupLayout(panelTarjetaTokens);
        panelTarjetaTokens.setLayout(panelTarjetaTokensLayout);
        panelTarjetaTokensLayout.setHorizontalGroup(
            panelTarjetaTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaTokensLayout.createSequentialGroup()
                .addGroup(panelTarjetaTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarjetaTokensLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblNumTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTarjetaTokensLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelTarjetaTokensLayout.setVerticalGroup(
            panelTarjetaTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaTokensLayout.createSequentialGroup()
                .addComponent(lblNumTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        panelTarjetaLineas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 5, true));
        panelTarjetaLineas.setPreferredSize(new java.awt.Dimension(250, 150));

        lblNumLineas.setFont(new java.awt.Font("Noto Sans", 0, 60)); // NOI18N
        lblNumLineas.setForeground(new java.awt.Color(0, 204, 0));
        lblNumLineas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumLineas.setText("2");

        jLabel1.setFont(new java.awt.Font("Noto Sans Black", 0, 13)); // NOI18N
        jLabel1.setText("Lineas con Tokens");

        javax.swing.GroupLayout panelTarjetaLineasLayout = new javax.swing.GroupLayout(panelTarjetaLineas);
        panelTarjetaLineas.setLayout(panelTarjetaLineasLayout);
        panelTarjetaLineasLayout.setHorizontalGroup(
            panelTarjetaLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLineasLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTarjetaLineasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        panelTarjetaLineasLayout.setVerticalGroup(
            panelTarjetaLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaLineasLayout.createSequentialGroup()
                .addComponent(lblNumLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panelTarjetaErrores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 5, true));
        panelTarjetaErrores.setPreferredSize(new java.awt.Dimension(250, 150));

        jLabel3.setFont(new java.awt.Font("Noto Sans Black", 0, 13)); // NOI18N
        jLabel3.setText("Errores");

        lblNumErrores.setFont(new java.awt.Font("Noto Sans", 0, 60)); // NOI18N
        lblNumErrores.setForeground(new java.awt.Color(255, 0, 0));
        lblNumErrores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumErrores.setText("2");

        javax.swing.GroupLayout panelTarjetaErroresLayout = new javax.swing.GroupLayout(panelTarjetaErrores);
        panelTarjetaErrores.setLayout(panelTarjetaErroresLayout);
        panelTarjetaErroresLayout.setHorizontalGroup(
            panelTarjetaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaErroresLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(panelTarjetaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTarjetaErroresLayout.createSequentialGroup()
                        .addComponent(lblNumErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTarjetaErroresLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93))))
        );
        panelTarjetaErroresLayout.setVerticalGroup(
            panelTarjetaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaErroresLayout.createSequentialGroup()
                .addComponent(lblNumErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Noto Sans Black", 0, 18)); // NOI18N
        jLabel4.setText("Frecuencia por tipo de token");

        tablaFrecuencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTabla.setViewportView(tablaFrecuencia);

        btnCerrarEstadistica.setText("Cerrar");
        btnCerrarEstadistica.addActionListener(this::btnCerrarEstadisticaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTarjetaTokens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(panelTarjetaLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(panelTarjetaErrores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCerrarEstadistica)
                        .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTarjetaTokens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTarjetaLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTarjetaErrores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarEstadistica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarEstadisticaActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarEstadisticaActionPerformed

    /**
     * @param args the command line arguments
     */

        //</editor-fold>

        /* Create and display the dialog */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarEstadistica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNumErrores;
    private javax.swing.JLabel lblNumLineas;
    private javax.swing.JLabel lblNumTokens;
    private javax.swing.JPanel panelTarjetaErrores;
    private javax.swing.JPanel panelTarjetaLineas;
    private javax.swing.JPanel panelTarjetaTokens;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaFrecuencia;
    // End of variables declaration//GEN-END:variables
}
